### ISSUE TITLE
Files from DC 2.42 not fully supported

### ISSUE THREAD

**Issue by ByteProject** [Utodev/undaad#3]
When decompiling DDB files produced with DC 2.42, the output seems to result in non-working files, both SCE and also .DSF when the -D flag is used. From what I see in the output, it seems to be not parsing tokens properly. The DDBs I'm processing have max. text compression that had been introduced with 2.42 applied to LTX/MTX/STX.

**Comment by Utodev** [comment]
I found a bug which was making undaad skip first token, so it that token was not replaced while "undaading". It should be fixed now.
