### ISSUE TITLE
C64 decompilation fails

### ISSUE THREAD

**Issue by ByteProject** [Utodev/undaad#4]
When decompiling Commodore 64 databases that already have a Commodore header (which is probably the common scenario when you want to use a decompiler), you get an offset error. Decompilation only works when the C64 DDB does not have a header. This should be changed.

**Comment by Utodev** [comment]
I've uploaded new version that allows an additional parameter for the offset where the DDB data si:

You can now do this:

php undaad.php file.ddb -O 2, which means skip two bytes (C64 header). Also, it would allow reading DDB data from an snapshot, or any other file (i.e. the CPC .bin file) , if you know where the DDB data is located. Parameter is "-O n" where n is the number of bytes to ignore/skip.
